language: android

android:
  components:
   - tools
   - platform-tools
   - build-tools-26.0.2
   - android-19

notifications:
  email:
    on_success: change
    on_failure: always

before_install:
 # Install NDK + openconnect build deps
 - sudo apt-get update -qq
 - sudo apt-get install -qq build-essential autoconf automake libtool groff expect ant
 - FORCE_PKG=android_ndk ./misc/fetch.sh android-ndk-r16b-linux-x86_64.zip bcdea4f5353773b2ffa85b5a9a2ae35544ce88ec5b507301d8cf6a76b765d901
 - sudo mkdir -p /opt/android-sdk-linux_x86
 - sudo unzip -d /opt/android-sdk-linux_x86 -q android-ndk-r16b-linux-x86_64.zip

script:
 - make -C external
 - ./gradlew assembleDebug

after_success:
 - mkdir -p artifacts/ics-openconnect/{arm,arm64,x86,x86_64}
 - ln -s artifacts/ics-openconnect out
 - cp app/build/outputs/apk/debug/app-debug.apk out/OpenConnect-debug.apk
 - cp app/libs/* out/
 - cp app/src/main/jniLibs/armeabi/* out/arm/
 - cp app/src/main/jniLibs/arm64-v8a/* out/arm64/
 - cp app/src/main/jniLibs/x86/* out/x86/
 - cp app/src/main/jniLibs/x86_64/* out/x86_64/
 # skip directories (will return an error code)
 - cp external/arm/* out/arm/ || true
 - cp external/arm64/* out/arm64/ || true
 - cp external/x86/* out/x86/ || true
 - cp external/x86_64/* out/x86_64/ || true
 - cp external/arm/openconnect/android/arm-linux-androideabi/out/sbin/openconnect out/arm/
 - cp external/arm64/openconnect/android/aarch64-linux-android/out/sbin/openconnect out/arm64/
 - cp external/x86/openconnect/android/i686-linux-android/out/sbin/openconnect out/x86/
 - cp external/x86_64/openconnect/android/x86_64-linux-android/out/sbin/openconnect out/x86_64/

deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: NuE53r3/7Em/XA7bszXh3KEiZPCbcbQpIc1eI3u+2HYlxBa7VuVz046GrIF75Lw/mtKILsqHW2RNcdv0poLa3r7xGxjKwaxFe3SfioeSQi3B1SYE0bSqWtRUX0+uFasESXXQVhVckrDM5bRsNPQgaAZZqzdEyOIad3XtTQx91onqjZpJPhdJFrvMcRTjHrcZ/m1EP7HarWWRuTkmQuHOBLMUdTIl/F5t1VJK4mLtx5F4VebbrNw1yfAmyV7v13dMAQ0GdaAX7uW522dDTMDVVdYFL+h6lWwf62zulqr7aEjjx0/eTlzzzarztxUqdrJ9I1kUwLUuiftW72GYLYMmReSYIdRycd4kU1G1Da219d74705PABECx0kS+sNYiZbB5trQAcR89iNpVTuAXtSAm/3oG9jG1MhF78Aw2UoS0sJKJ1vf8+ezZ5shTXXytBoE8/KpDI1eQDIgqPKhXvRNmaQ5UOsgKDQBc8H4wOyB4ZM08nyPqF5hdpgR4tl1NC6iZiLD6Vs1Gej75uFbmQF8+8IvcxgH6EPFBdjBIl6GC3O8oboPHfpJGjtHjLyb24vBsKfcCQ7jipv69+3nUzjVFBL4+eD6yy8PYUJTfjewXfnRKaRO+Ig4QZOlBRET1+CiouuRoYnWL25/HIKGRSOPx4rz2WdbkA+4OeIiCKz+X2w=
  file: artifacts/ics-openconnect/OpenConnect-debug.apk
  draft: true
  on:
    repo: loplex/ics-openconnect-android-gui
    branch: next

